
[workspace.package]
authors = ["PartiQL Team <partiql-team@amazon.com>"]
description = "PartiQL Beamline"
#homepage = TODO
#repository = TODO
license = "Apache-2.0"
readme = "../README.md"
#keywords = TODO
#categories = TODO
exclude = [
  "**/.git/**",
  "**/.github/**",
  "**/.travis.yml",
  "**/.appveyor.yml",
]
edition = "2021"
version = "0.1.0"

[patch.crates-io]
# TODO Until at least 0.7.2 is released
partiql-types = { git = "https://github.com/partiql/partiql-lang-rust" }
[workspace]
members = [
    "partiql-beamline-sim",
    "partiql-beamline-cliargs",
    "partiql-beamline-cli",
]
resolver = "2"

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3

[profile.bench]
debug = true
lto = true
