[workspace.package]
authors = ["PartiQL Team <partiql-team@amazon.com>"]
description = "PartiQL Beamline"
#homepage = TODO
#repository = TODO
license = "Apache-2.0"
readme = "../README.md"
#keywords = TODO
#categories = TODO
exclude = [
    "**/.git/**",
    "**/.github/**",
    "**/.travis.yml",
    "**/.appveyor.yml",
]
edition = "2021"
version = "0.1.0"

[workspace]
members = [
    "partiql-beamline-cli",
    "partiql-beamline-cliargs",
    "partiql-beamline-query",
    "partiql-beamline-sim",
    "partiql-beamline-serde",
]
resolver = "2"

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3

[profile.bench]
debug = true
lto = true

[patch.crates-io]
partiql-parser = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }
partiql-ast = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }
partiql-types = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }
partiql-value = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }
partiql-common = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }
partiql-extension-ddl = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }
partiql-extension-ion = { git = "https://github.com/partiql/partiql-lang-rust", branch = "main" }