[package]
name = "partiql-beamline-cli"
description = "PartiQL Beamline CLI"
readme.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true
edition.workspace = true
version.workspace = true

[[bin]]
name = "beamline"
path = "src/main.rs"

[dependencies]
partiql-beamline = { path = "../partiql-beamline-sim", version = "0.1" }
partiql-beamline-cliargs = { path = "../partiql-beamline-cliargs", version = "0.1" }
partiql-beamline-serde = { path = "../partiql-beamline-serde", version = "0.1" }
partiql-beamline-query = { path = "../partiql-beamline-query", version = "0.1" }

partiql-extension-ddl = "0.10"
partiql-extension-ion = "0.10"
partiql-types = "0.10"
partiql-value = "0.10"

clap = { version = "4.4", features = ["derive", "wrap_help", "help", "usage", "error-context"] }
miette = { version = "7.2", features = ["fancy"] }

ion-rs = "0.18.1"

arrow = { version = "53", features = ["prettyprint"] }
parquet = { version = "53", features = ["arrow"] }

time = { version = "0.3", features = ["formatting", "parsing", "serde"] }

itertools = "0.13"

derive_builder = "0.20"
thiserror = "1"

[dev-dependencies]
tempfile = "3"
