[package]
name = "partiql-beamline-cli"
description = "PartiQL Beamline CLI"
readme.workspace = true
authors.workspace = true
license.workspace = true
#homepage = TODO
#repository = TODO
#keywords = TODO
#categories = TODO
exclude.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
partiql-beamline = { path = "../partiql-beamline-sim", version = "0.1" }
partiql-beamline-cliargs = { path = "../partiql-beamline-cliargs", version = "0.1" }

time = { version = "0.3", features = ["formatting", "parsing"] }

miette = { version ="5.*", features = ["fancy"] }
clap = { version = "4.4", features = ["derive", "wrap_help", "help", "usage", "error-context"] }
