[package]
name = "partiql-beamline"
description = "PartiQL Beamline"
readme.workspace = true
authors.workspace = true
license.workspace = true
#homepage = TODO
#repository = TODO
#keywords = TODO
#categories = TODO
exclude.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
partiql-value = "0.7"
partiql-types = "^0.7.2"
partiql-extension-ion = "0.7"

ion-rs = { version = "1.0.0-rc.3", features = ["experimental-reader", "experimental-lazy-reader"] }

dyn-clone = "1.0"

thiserror = "1.*"
miette = { version = "7.2", features = ["fancy"] }

derive_builder = "0.20"

once_cell = "1.19"
regex = "1.10"

time = "0.3"
uuid = "1.7"
rand = "0.8"
rand_chacha = "0.3"
rand_pcg = "0.3"
rand_distr = "0.4"
statrs = "0.16"
unicase = "2.*"


[features]
default = []
