[package]
name = "partiql-beamline"
description = "PartiQL Beamline"
readme.workspace = true
authors.workspace = true
license.workspace = true
#homepage = TODO
#repository = TODO
#keywords = TODO
#categories = TODO
exclude.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
partiql-value = "0.8"
partiql-types = "0.8"
partiql-extension-ion = "0.8"

# TODO: move to stable `ion-rs` once available
ion-rs = { version = "1.0.0-rc.5", features = ["experimental"] }
ion-rs_old = { version = "0.18", package = "ion-rs" }

itertools = "0.13"

dyn-clone = "1.0"

thiserror = "1.*"
miette = { version = "7.2", features = ["fancy"] }

derive_builder = "0.20"

once_cell = "1.19"
regex = "1.10"

uuid = "1.7"
rand = "0.8"
rand_chacha = "0.3"
rand_pcg = "0.3"
rand_distr = "0.4"
statrs = "0.16"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
unicase = "2.*"

lipsum = "0.9"
regex-syntax = "0.8"

debug-ignore = "1"

time = { version = "0.3", features = ["formatting", "parsing", "serde"] }

[dev-dependencies]
assert_matches = "1.5"

[features]
default = []
