[package]
name = "partiql-beamline-query"
description = "PartiQL Beamline Query Inferenct and Generation"
readme.workspace = true
authors.workspace = true
license.workspace = true
#homepage = TODO
#repository = TODO
#keywords = TODO
#categories = TODO
exclude.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
partiql-beamline = { path = "../partiql-beamline-sim", version = "0.1" }

partiql-parser = "0.9"
partiql-ast = "0.9"
partiql-extension-ion = "0.9"
partiql-value = "0.9"
partiql-types = "0.9"


petgraph = "0.6.5"

bitflags = "2.6"

itertools = "0.13"

thiserror = "1.*"
miette = { version = "7.2", features = ["fancy"] }
clap = { version = "4.4", features = ["derive", "wrap_help", "help", "usage", "error-context"] }

time = { version = "0.3", features = ["formatting", "parsing"] }
rand = "0.8"
rand_chacha = "0.3"
rand_pcg = "0.3"
rand_distr = "0.4"
statrs = "0.17"
dyn-clone = "1.0.17"

rust_decimal = "1.35"


[dev-dependencies]
insta = "1.38.0"