[package]
name = "partiql-beamline-serde"
description = "PartiQL Beamline SerDe"
readme.workspace = true
authors.workspace = true
license.workspace = true
#homepage = TODO
#repository = TODO
#keywords = TODO
#categories = TODO
exclude.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
partiql-beamline = { path = "../partiql-beamline-sim", version = "0.1" }
partiql-types = "0.10"
partiql-extension-ddl = "0.10"
ion-rs = "0.18.1"
miette = { version = "7.2", features = ["fancy"] }
thiserror = "1.*"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
